### ISSUE TITLE
Segmentation fault when checking an sfv file

### ISSUE THREAD

**Issue by jonesnc** [Wunkolo/qCheck#3]
I compiled this on a Rasp. Pi 4 running 64-bit Ubuntu Server 21.04 by running the following:

```bash
$ git clone https://github.com/Wunkolo/qCheck && cd qCheck

$ mkdir build-dir && cd build-dir

$ cmake ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/floodadmin/qCheck/build-dir

$ make
Scanning dependencies of target qCheck
[ 50%] Building CXX object CMakeFiles/qCheck.dir/source/main.cpp.o
[100%] Linking CXX executable qCheck
[100%] Built target qCheck
```

When I try to run `qCheck --check test.sfv`, I get:
```bash
Segmentation fault (core dumped)
```

Is this code not expected to run on an ARM processor? Did I compile something incorrectly?

**Comment by Wunkolo** [comment]
Can verify I get this issue as well on an x86-based system. Seems to be a logical error with the `--check` option being passed multiple options, when it only consumes one.

With a simple test sfv file, I get a segfault when I use `--check` on a single file but no output with `-c`. A regression seems to have happened. Will look into it!

**Comment by jonesnc** [comment]
> A regression seems to have happened. Will look into it!

Thanks!

**Comment by Wunkolo** [comment]
Try out the latest! https://github.com/Wunkolo/qCheck/commit/389e06c5148fde4dc641d0b075021d6519058c06

I've done some bug fixes and added the ability to consume the input list of files as either a list of input files to checksum or a list of `.sfv` files to verify, allowing both `qCheck --check test.sfv` and even `qCheck --check *.sfv`. Lemme know how it goes!

**Comment by jonesnc** [comment]
I tested the latest commit, and it looks like `--check` is fixed and works for a single file and for multiple files with `*.sfv`.

`-c` is still printing empty output, but I'm not sure if you meant to fix that already.

Thanks for your work on this!

**Comment by Wunkolo** [comment]
Ah! Another regression while fixing the previous regression. It still thinks `-c` consumes arguments, so using `-c` would cause the argument after it to be ignored.  Just more confusing `getopt` stuff. First time using it.

Fixed in https://github.com/Wunkolo/qCheck/commit/c7c0d5805b8fde5e2d77d6bcb1e3391b2f26efbf!

**Comment by jonesnc** [comment]
Looks like that fixed `-c`.
